In [1]:
import pandas as pd
import kagglehub

from glob import glob

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
path = kagglehub.dataset_download("mirichoi0218/insurance")

df = pd.read_csv(glob(path + "/**/*.csv", recursive=True)[0])

df.head()

Downloading to /root/.cache/kagglehub/datasets/mirichoi0218/insurance/1.archive...

100%|██████████| 16.0k/16.0k [00:00<00:00, 20.0MB/s]

Extracting files...

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
print(df.isnull().sum())

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [4]:
le = LabelEncoder()

df["smoker"] = le.fit_transform(df["smoker"])

df.head()

   age     sex     bmi  children  smoker     region      charges
0   19  female  27.900         0       1  southwest  16884.92400
1   18    male  33.770         1       0  southeast   1725.55230
2   28    male  33.000         3       0  southeast   4449.46200
3   33    male  22.705         0       0  northwest  21984.47061
4   32    male  28.880         0       0  northwest   3866.85520

In [5]:
X = df[["age", "bmi", "children", "smoker"]]

y = df["charges"]

In [6]:
x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [7]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [8]:
model = LinearRegression()

In [9]:
model.fit(x_train, y_train)

LinearRegression()

In [10]:
y_pred = model.predict(x_test)

print("Predicted Values:")
print(y_pred)

print()

print("Actual Values:")
print(y_test.values)

Predicted Values:
[ 8550.90921341  6969.71599759 36794.13661808  9421.86824203
 26875.01095777 11101.26514111   141.44896605 16750.22436643
   743.78364016 11157.63586446 28521.42342227  9296.15962897
  5456.5831315  38513.59317763 40362.63211366 37226.61219261
 15312.47750251 36042.83494384  9322.40796481 31395.64230108
  4273.49461256 10468.62243337  2723.96491222  6575.5287315
 11228.01912269 12468.20703945 14803.23875441  6062.13408867
  9531.77127863  2381.73787018  9470.9842188  12959.38866372
  4702.13338911  3410.73606761  4819.65393639 12488.16536441
  2355.2166747   9157.11135848 33234.15784494 32746.6948439
  4270.42403098  4233.52485656 14431.41993531 11388.84943272
  8929.60714179 12484.19557109  5150.40526844  3550.1037231
 35652.7853174   9280.12457197 15967.47938558  2556.74541518
 12158.95859481  1066.73450634 13555.51395976 12107.63444981
  3933.78585209 32050.44566484 13634.05117632 12397.82378122
 14493.62754566 10572.23545909 16669.43245629  7717.46643965
 11362.88637442  4002.4167569  27060.76239206 11178.82251312
  2111.07588471  6475.63432902 10213.54238103 11141.5791179
 11138.66980194  9355.18191748 12086.76718615  6936.96373448
  6777.77103761 10679.86525877  6743.56411652  9150.05856568
  3940.67737927 36217.76500227  6723.77632884 30313.42802916
 34840.04196096 34813.10220435  7216.54904091 12756.39284735
  9841.41659483 14776.62450822 17152.71129233 35518.43596997
 32602.2097042   5760.89390088 32155.61881714  9823.47106503
 29664.84331513  3832.59491101 28277.4190621   5420.13393472
  5325.53997161  2232.68096558 11608.90352975 15384.07666653
 11311.8133995   4466.20235446 10100.12536594 32006.13093351
  -457.8833414  33081.82571402  3608.27601617 10233.60302836
 13830.34769234 31158.27829801 10987.75822155  4259.79488196
 12672.70403915 32189.45055622  8336.65474969  3183.78071645
  7940.67175106 10478.51632722 14675.34366266  5797.59426775
  3745.09442887 10105.14052777 11037.09126095 10676.61172201
 14578.91985956  7522.03502791  5584.43169789  9402.59206618
  9479.77694712 11990.33096515  8651.44238589 15628.41282959
  7909.8082712  32158.80413898 35604.27400317 31128.91600147
  5942.93254912 12101.48401499  6167.62662597 14395.31181308
  2740.13639904 33371.60260973  6212.80691687  5383.03938723
 14192.06482663  7297.05567351 38514.99203859  3005.49794513
  5984.4868122  31204.19968127 11364.78442932  7980.19152943
 14338.08840334 10011.80899581 27264.76288877 32980.7370953
 14070.85976356  1626.54703542 13574.45833273  1823.14124689
  5787.15150838 11711.60492583 40079.2227154  36394.79776034
 33542.30197781  4233.63959682  7882.84367879  8980.38556751
 11879.17791531  4773.63023076  2414.35370347 32368.03102297
 25492.86545456 17593.5951415  26435.25310993 10127.95551792
 36817.09730971  -784.08774433  6802.0872111   8088.05693506
  3993.76045841  4973.87485055  5472.95926306  4667.43654574
 15235.79496174 11076.20174985  7228.25108519  2062.40330486
  1130.46498958 32248.81391928 16539.04048429 12162.07570174
  1222.05658602 12078.02098319  1128.96380625  9121.0621795
  1847.60312185 33864.85597242 10932.51035329  2551.58140563
 25895.46712072 26583.24295645  9386.35551068  1789.77190334
 13372.374146    1549.37457238 10830.32102434 10817.17359374
 16306.61101024 27082.74907633  7198.41128428  4742.76675089
  6052.53789027 13446.67798125 11341.32454375  8512.16463487
  4980.52762554 12137.7502566  13915.78570773 35910.10764543
  4055.24208524 29110.04594788  -485.75687249  2786.19421212
 11256.25856414 15770.57506077  5350.62819867  6905.3374727
  4249.44517329 31695.32550853  7255.75258051 12548.62062134
  5533.43620954  9848.43528017 36409.61376531  4598.92965286
  9312.32184413 31472.6534985   5604.32180795  4793.45212591
  1012.65916476  4741.26556756  4942.18964551  6853.36483075
 18698.30799775 -1507.6274815   2719.01796529 11008.92003441
  3531.00123076  9816.80901838  3617.88463247  5292.95824578
 12772.59844163  6101.90503712  7853.58370462  7121.53337044
  8843.99544289 10471.71785075 28024.34253326 39224.38864825
 11691.84197393  7257.65063541 40945.82704174 12622.0279358 ]

Actual Values:
[ 9095.06825   5272.1758   29330.98315   9301.89355  33750.2918
  4536.259     2117.33885  14210.53595   3732.6251   10264.4421
 18259.216     7256.7231    3947.4131   46151.1245   48673.5588
 44202.6536    9800.8882   42969.8527    8233.0975   21774.32215
  5080.096     7441.501     1256.299     2755.02095  11085.5868
 10923.9332   12644.589    18804.7524    9715.841     1131.5066
 15828.82173  11842.62375   2020.5523    5693.4305    2904.088
  7448.40395   2597.779     7337.748    23887.6627   38709.176
  4687.797     2643.2685   11674.13     12124.9924    4889.9995
 12333.828     3579.8287    4391.652    42124.5153    4463.2051
 13887.204     1719.4363   28476.73499   1708.92575  10594.2257
 25333.33284   3645.0894   38746.3551   11848.141    10564.8845
 13880.949     4753.6368   27941.28758   8017.06115  23045.56616
  4133.64165  17942.106    25992.82104   3594.17085   1682.597
  6079.6715    9411.005     8283.6807    6338.0756    7152.6714
  4889.0368    4846.92015  11454.0215    4349.462     9101.798
  1391.5287   28101.33305   5152.134    38511.6283   44501.3982
 41097.16175   4837.5823   10601.63225   8310.83915  11264.541
 15230.32405  27037.9141   23401.30575   5031.26955  38282.7495
  6875.961    19719.6947    1880.07     18765.87545   6402.29135
  4527.18295   1743.214     5709.1644   12363.547    13129.60345
  1727.54      7731.4271   21195.818     1702.4553   23244.7902
 23082.95533   2927.0647   13019.16105  37701.8768    9778.3472
  1980.07     30259.99556  22478.6       6313.759     2789.0574
  5594.8455    7261.741    11396.9002    1986.9334    4719.73655
  7749.1564    7345.7266    9288.0267   12244.531     1837.2819
  3972.9247    5934.3798    5836.5204    7935.29115   5649.715
 12347.172    12404.8791   22144.032    42983.4585   37270.1512
  5267.81815   9866.30485   2322.6218   33471.97189   2137.6536
 23306.547     5261.46945   3761.292    11436.73815   4751.07
 46661.4424    2690.1138    1146.7966   37607.5277    6373.55735
  4518.82625  13555.0049    8547.6913   34439.8559   39125.33225
 13607.36875   2710.82855  14988.432     2396.0959    3591.48
  7162.0122   48824.45     43578.9394   39556.4945    2632.992
  9182.17      6238.298     5757.41345   4239.89265   2154.361
 21978.6769   16297.846    13831.1152   32734.1863   11830.6072
 29523.1656    3167.45585   8428.0693    5012.471     5209.57885
  2855.43755  20277.80751   3554.203     8569.8618   10594.50155
  3597.596     7323.734819  2731.9122   38711.       12981.3457
  9283.562     2709.1119   12096.6512    2198.18985   8932.084
  3176.2877   24393.6224    4266.1658   22493.65964  17085.2676
 16577.7795    8827.2099    4296.2712    7804.1605    3208.787
 12957.118    22192.43711   9432.9253   17043.3414    6593.5083
  4137.5227    4779.6023   14001.2867   12629.8967    5245.2269
  2404.7338    6948.7008    6435.6237   42560.4304    2055.3249
 34672.1472    1731.677     1639.5631    9377.9047   10977.2063
  1534.3045    9644.2525    4529.477    37829.7242    9991.03765
  8125.7845    3877.30425   5979.731    43896.3763    1674.6323
 13204.28565  44585.45587   3021.80915   3392.9768    1632.03625
  2699.56835  20177.67113   4076.497    12592.5345    1621.3402
  1875.344     7196.867     3161.454    12029.2867    2719.27975
 18218.16139  12146.971     3292.52985   8688.85885   6113.23105
  8059.6791   13415.0381   18246.4955   47055.5321   12222.8983
  6067.12675  63770.42801   9872.701   ]

In [11]:
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 4213.798594527246
MSE: 33981653.95019775
R2 Score: 0.7811147722517887